#!/usr/bin/env bash

set -x

chown root:root /etc/systemd/system/powertop.service
chown root:root /etc/udev/rules.d/power_supply.rules
chown root:root /usr/local/bin/async-start-powertop
chown root:root /usr/local/bin/async-stop-powertop

chmod 644 /etc/systemd/system/powertop.service
chmod 644 /etc/udev/rules.d/power_supply.rules
chmod 755 /usr/local/bin/async-start-powertop
chmod 755 /usr/local/bin/async-stop-powertop
