#!/usr/bin/env bash

chown root:root /etc/systemd/system/powertop.service
chown root:root /etc/udev/rules.d/power_supply.rules
find /usr/local/bin -type f -name "async-*-powertop" -exec chown root:root {} \;

chmod 644 /etc/systemd/system/powertop.service
chmod 644 /etc/udev/rules.d/power_supply.rules
find /usr/local/bin -type f -name "async-*-powertop" -exec chmod 755 {} \;
