name: release

on:
  push:
    tags:
      - '*.*.*'    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PACKAGE_NAME: powertop-systemd-service
  MAINTAINER: 'carniz'
  DESC: 'A powertop SystemD service with accompanying udev rules that starts/stops the service when the battery charging status changes.'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: battila7/get-version-action@v2
        id: get_version

      - name: Prepare sources
        run: bash .github/prepare-sources.sh ${{ steps.get_version.outputs.version }}

      - name: List debian build root
        run: sudo apt-get install -y tree && tree -p ${{ env.PACKAGE_NAME }}-${{ steps.get_version.outputs.version }}

      - name: Build Debian package 
        run: dpkg-deb --build ${{ env.PACKAGE_NAME }}-${{ steps.get_version.outputs.version }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ steps.get_version.outputs.version }}.deb
          path: |
            ./*.deb
